services:
  - type: web
    name: holidiaapis
    runtime: node
    repo: https://github.com/omkhetwal/holidiaapis
    plan: free
    envVars:
      - key: BUN_VERSION
        value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start
version: "1"
